name: ReplicationDickens
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - georasters
  - geopandas
  - pandas
  - pandas-datareader
  - spatialpandas
  - statsmodels
  - xlrd
  - dask
  - networkx
  - ipykernel
  - ipyparallel
  - ipython
  - ipython_genutils
  - ipywidgets
  - kiwisolver
  - matplotlib-base
  - matplotlib
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - geoplot
  - geopy
  - geotiff
  - pycountry
  - nb_conda_kernels
  - stata_kernel
  - plotly
  - nodejs
  - geocoder
  - camelot-py
  - html5lib
  - ghostscript
  - plotnine
  - ipympl
  - git
  - ipumspy
  - dask-geopandas
  - python-kaleido
  - numba
  - jupyter
  - jupyterlab
  - numpy
  - openpyxl
  - opencv
  - jinja2
  - rasterstats
  - pip:
      - geonamescache
      - stargazer
      - ipystata
      - pyfixest
      - isounidecode
