name: EconGrowthUG
channels:
  - conda-forge
dependencies:
  - python=3.10 
  - pandas 
  - geopandas 
  - rpy2 
  - statsmodels 
  - seaborn 
  - geoplot 
  - matplotlib 
  - jupyter 
  - jupyterlab 
  - numpy 
  - openpyxl 
  - pandas-datareader 
  - xlrd 
  #- dask 
  #- dask-core 
  #- dask-geopandas 
  - georasters 
  - stargazer 
  - scipy
  - pip:
      - stargazer
      - binsreg 
