name: EconGrowthUG
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _r-mutex
  - access
  - affine
  - alsa-lib
  - amply
  - aom
  - asttokens
  - attr
  - attrs
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - backcall
  - backports
  - backports.functools_lru_cache
  - backports.zoneinfo
  - beautifulsoup4
  - binutils_impl_linux-64
  - blosc
  - boost-cpp
  - branca
  - brotli
  - brotli-bin
  - brotli-python
  - brunsli
  - bwidget
  - bzip2
  - c-ares
  - c-blosc2
  - ca-certificates
  - cairo
  - camelot-py
  - cartopy
  - certifi
  - cffi
  - cfitsio
  - chardet
  - charls
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - cloudpickle
  - coin-or-cbc
  - coin-or-cgl
  - coin-or-clp
  - coin-or-osi
  - coin-or-utils
  - coincbc
  - colorama
  - comm
  - conda
  - conda-package-handling
  - conda-package-streaming
  - contextily
  - contourpy
  - coverage
  - cryptography
  - curl
  - cycler
  - dask-core
  - dask-geopandas
  - distributed>=2021.06.0
  - dav1d
  - dbus
  - debugpy
  - decorator
  - deprecation
  - descartes
  - docopt
  - docutils
  - entrypoints
  - esda
  - et_xmlfile
  - executing
  - expat
  - ffmpeg
  - fiona
  - fmt
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freeglut
  - freetype
  - freexl
  - fribidi
  - fsspec
  - future
  - gcc_impl_linux-64
  - gdal
  - geocoder
  - geographiclib
  - geopandas
  - geopandas-base
  - geoplot
  - geopy
  - georasters
  - geos
  - geotiff
  - gettext
  - gflags
  - gfortran_impl_linux-64
  - ghostscript
  - giddy
  - giflib
  - git
  - glib
  - glib-tools
  - glog
  - gmp
  - gmpy2
  - gnutls
  - graphite2
  - gsl
  - gst-plugins-base
  - gstreamer
  - gxx_impl_linux-64
  - harfbuzz
  - hdf4
  - hdf5
  - html5lib
  - icu
  - idna
  - imagecodecs
  - imageio
  - importlib_metadata
  - inequality
  - ipumspy
  - ipykernel
  - ipympl
  - ipyparallel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jasper
  - jedi
  - jinja2
  - joblib
  - json-c
  - jupyter_client
  - jupyter_core
  - jupyterlab_widgets
  - jxrlib
  - kaleido-core
  - kealib
  - kernel-headers_linux-64
  - keyutils
  - kiwisolver
  - krb5
  - lame
  - lazy_loader
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libabseil
  - libaec
  - libarchive
  - libarrow
  - libass
  - libavif
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcap
  - libcblas
  - libclang
  - libclang13
  - libcrc32c
  - libcups
  - libcurl
  - libdeflate
  - libdrm
  - libedit
  - libev
  - libevent
  - libexpat
  - libffi
  - libflac
  - libgcc-devel_linux-64
  - libgcc-ng
  - libgcrypt
  - libgdal
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libglu
  - libgomp
  - libgoogle-cloud
  - libgpg-error
  - libgrpc
  - libhwloc
  - libiconv
  - libidn2
  - libjpeg-turbo
  - libkml
  - liblapack
  - liblapacke
  - libllvm14
  - libllvm15
  - libmamba
  - libmambapy
  - libnetcdf
  - libnghttp2
  - libnsl
  - libnuma
  - libogg
  - libopenblas
  - libopencv
  - libopenvino
  - libopenvino-auto-batch-plugin
  - libopenvino-auto-plugin
  - libopenvino-hetero-plugin
  - libopenvino-intel-cpu-plugin
  - libopenvino-intel-gpu-plugin
  - libopenvino-ir-frontend
  - libopenvino-onnx-frontend
  - libopenvino-paddle-frontend
  - libopenvino-pytorch-frontend
  - libopenvino-tensorflow-frontend
  - libopenvino-tensorflow-lite-frontend
  - libopus
  - libpciaccess
  - libpng
  - libpq
  - libprotobuf
  - libpysal
  - librttopo
  - libsanitizer
  - libsndfile
  - libsodium
  - libsolv
  - libspatialindex
  - libspatialite
  - libsqlite
  - libssh2
  - libstdcxx-devel_linux-64
  - libstdcxx-ng
  - libsystemd0
  - libtasn1
  - libthrift
  - libtiff
  - libunistring
  - libutf8proc
  - libuuid
  - libuv
  - libv8
  - libva
  - libvorbis
  - libvpx
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libxslt
  - libzip
  - libzlib
  - libzopfli
  - llvmlite
  - locket
  - lxml
  - lz4-c
  - lzo
  - make
  - mamba
  - mapclassify
  - markupsafe
  - mathjax
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mercantile
  - mgwr
  - mizani
  - momepy
  - mpc
  - mpfr
  - mpg123
  - mpmath
  - munch
  - munkres
  - mysql-common
  - mysql-libs
  - nb_conda_kernels
  - ncurses
  - nest-asyncio
  - nettle
  - networkx
  - nltk
  - nodejs
  - nspr
  - nss
  - numba
  - numpy
  - ocl-icd
  - ocl-icd-system
  - opencv
  - openh264
  - openjpeg
  - openpyxl
  - openssl
  - orc
  - p11-kit
  - packaging
  - pandas
  - pandas-datareader
  - pango
  - param
  - parso
  - partd
  - patsy
  - pcre2
  - pdfminer.six
  - perl
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - platformdirs
  - plotly
  - plotnine
  - pluggy
  - ply
  - pointpats
  - pooch
  - poppler
  - poppler-data
  - postgresql
  - proj
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pugixml
  - pulp
  - pulseaudio-client
  - pure_eval
  - py-opencv
  - pybind11-abi
  - pycosat
  - pycountry
  - pycparser
  - pycryptodome
  - pygeos
  - pygments
  - pyopenssl
  - pyparsing
  - pypdf2
  - pyproj
  - pyqt
  - pyqt5-sip
  - pysal
  - pyshp
  - pysocks
  - python
  - python-dateutil
  - python-kaleido
  - python_abi
  - pytz
  - pywavelets
  - pyzmq
  - qt-main
  - quantecon
  - r-base
  - r-boot
  - r-curl
  - r-dagitty
  - r-jsonlite
  - r-mass
  - r-rcpp
  - r-v8
  - rasterio
  - rasterstats
  - ratelim
  - rdma-core
  - re2
  - readline
  - regex
  - reproc
  - reproc-cpp
  - requests
  - retrying
  - rocm-smi
  - rtree
  - ruamel.yaml
  - ruamel.yaml.clib
  - s2n
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - seaborn-base
  - sed
  - segregation
  - setuptools
  - shapely
  - simplejson
  - sip
  - six
  - snappy
  - snuggs
  - soupsieve
  - spaghetti
  - spatialpandas
  - spglm
  - spint
  - splot
  - spopt
  - spreg
  - spvcm
  - sqlite
  - stack_data
  - stata_kernel
  - statsmodels
  - svt-av1
  - sympy
  - sysroot_linux-64
  - tbb
  - tenacity
  - threadpoolctl
  - tifffile
  - tiledb
  - tk
  - tktable
  - tobler
  - toml
  - tomli
  - toolz
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzcode
  - tzdata
  - ucx
  - unicodedata2
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - x264
  - x265
  - xcb-util
  - xcb-util-image
  - xcb-util-keysyms
  - xcb-util-renderutil
  - xcb-util-wm
  - xerces-c
  - xkeyboard-config
  - xlrd
  - xorg-fixesproto
  - xorg-inputproto
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-libxrender
  - xorg-libxt
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xf86vidmodeproto
  - xorg-xproto
  - xyzservices
  - xz
  - yaml
  - yaml-cpp
  - zeromq
  - zfp
  - zipp
  - zlib
  - zlib-ng
  - zstandard
  - zstd
  - pip:
      - anyio
      - dbnomics
      - exceptiongroup
      - geonamescache
      - h11
      - httpcore
      - httpx
      - importlib-metadata
      - pyarrow
      - pyyaml
      - sniffio
      - stargazer
