name: ReplicationDickens
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - pip=23.1.2
  - georasters=0.5.27
  - geopandas=0.13.2
  - pandas=1.5.3
  - pandas-datareader=0.10.0
  - spatialpandas=0.4.8
  - statsmodels=0.14.0
  - xlrd=2.0.1
  - dask
  - networkx=3.1
  - ipykernel=6.25.1
  - ipyparallel=8.6.1
  - ipython=8.14.0
  - ipython_genutils=0.2.0
  - ipywidgets
  - kiwisolver=1.4.4
  - matplotlib-base=3.7.2
  - matplotlib=3.7.2
  - scikit-image=0.21.0
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - seaborn=0.12.2
  - geoplot=0.5.1
  - geopy=2.3.0
  - geotiff=1.7.1
  - pycountry=22.3.5
  - nb_conda_kernels=2.3.1
  - stata_kernel=1.12.2
  - plotly=5.16.0
  - nodejs=20.1.0
  - geocoder=1.38.1
  - camelot-py=0.9.0
  - html5lib=1.1
  - ghostscript=9.54.0
  - plotnine=0.12.2
  - ipympl=0.9.3
  - git=2.41.0
  - ipumspy=0.4.1
  - dask-geopandas=0.3.1
  - python-kaleido=0.2.1
  - numba=0.57.1
  - jupyter
  - jupyterlab=4.0.11
  - numpy=1.24.4
  - openpyxl=3.1.2
  - opencv=4.8.0
  - jinja2=3.1.2
  - rasterstats=0.19.0
  - pip:
      - geonamescache==2.0.0
      - stargazer==0.0.6
      - ipystata
      - pyfixest
      - isounidecode